# import=[ '~/.config/alacritty/themes/thelovelace.toml' ]
# import=[ '~/.config/alacritty/themes/nightfox.toml' ]
# import=[ '~/.config/alacritty/themes/blood_moon.toml' ]

# [shell] 
# program="/usr/bin/zsh"

[env]
TERM = "xterm-256color"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[font]
size=16

[font.bold]
family="ComicShannsMonoNerdFont"
style="Bold"

[font.normal]
family="ComicShannsMonoNerdFont"
style="Regular"

[cursor]
style={ blinking="Always" }
blink_interval=500
thickness=0.05

[window]
decorations="None"
dynamic_padding=true
padding={x=10, y=5}
opacity=0.8
