return {
    transparent_bg = false,
    mason_ensure_installed = {
        "tailwindcss",
        "templ",
        "svelte",
        "cmake",
        "zls",
        "clangd",
        "gopls",
        "lua_ls",
        "html",
        "cssls",
        "htmx",
        "jsonls",
        "pylsp",
        "rust_analyzer",
        "tsserver",
        "bashls",
        "texlab",
    },
    colorscheme = "gruvbox",
}
