return {
	transparent_bg = true,
	mason_ensure_installed = {
		"cssls",
		"tailwindcss",
		"templ",
		"svelte",
		"cmake",
		"zls",
		"clangd",
		"lua_ls",
		"html",
		"cssls",
		"htmx",
		"jsonls",
		"pylsp",
		"rust_analyzer",
		"ts_ls",
		"bashls",
		"texlab",
	},
	-- colorscheme = "nightfox",
	-- colorscheme = "default",
	-- colorscheme = "kanagawa-dragon",
    -- colorscheme = "tokyonight",
    colorscheme = "vscode",
	-- colorscheme = "rose-pine-moon",
}
