#!/bin/bash

# reusable part of the build system that are likely to be called multiple times
# in certain circumstances, e.g. separate build steps for files written in
# different languages and multiple targets in the same project.

function _compile {
	echo "$COMMAND -o $2 $COMMAND_FLAG -c $1"
	$COMMAND -o $2 $COMMAND_FLAG -c $1
}

function _link_objects {
	echo "$COMMAND $* -o $TARGET $COMMAND_FLAG"
	$COMMAND $* -o $TARGET $COMMAND_FLAG
}

function _archive {
	echo "$COMMAND $COMMAND_FLAG lib$TARGET.a $*"
	$COMMAND $COMMAND_FLAG lib$TARGET.a $*
}

function _link_dynamic {
	echo "$COMMAND $* -o lib$TARGET.so --shared $COMMAND_FLAG"
	$COMMAND $* -o lib$TARGET.so --shared $COMMAND_FLAG
}
