#!/bin/bash

# configuration of buildling process

# object extension
OBJ_EXT='o'
# select which compiler to use
COMMAND=gcc
# send flags to compiler
COMMAND_FLAG=''
TARGET='main'

source ./build_util

function link_error {
	echo "ERROR: Failed to link"
	exit 1
}

_link_objects `for file in ./target/*.$OBJ_EXT; do echo $file; done` || link_error
