#!/bin/bash

# configuration of buildling process

# specify the command to use
COMMAND=gcc
# send additional flags to command
COMMAND_FLAG=''
# specify the target name for the stage
TARGET='main'

source ./build_util

function link_error {
	echo "ERROR: Failed to link"
	exit 1
}

_link_objects `for file in ./target/*.o; do echo $file; done` || link_error
