require("config.catppuccin-nvim")
require("config.comment")
require("config.evergarden")
require("config.gruvbox")
require("config.kanagawa-nvim")
require("config.nvim-cmp")
require("config.lspconfig")
require("config.mason")
require("config.mellifluous")
require("config.nightfox")
-- require("config.conform-nvim")
-- require("config.nvim-tree")
require("config.oil-nvim")
require("config.nvim-treesitter")
require("config.rose-pine")
require("config.telescope")
require("config.trouble-nvim")
require("config.tokyonight-nvim")
