#!/bin/bash

if ! [[ -d "$1" ]]; then
    mkdir $1
fi

function cp_file_in_dir {
    cd $1
    while read -r file; do
        if [[ -d $file ]]; then
            if ! [[ -d $2/$file ]]; then
                mkdir $2/$file
            fi
            cp_file_in_dir $file "$2/$file"
        elif [[ -f $file ]]; then
            cp $file $2/
        fi
    done <<< $(git ls-files 2> /dev/null)
}

for file in $2; do
    echo $file
    if [[ -d $file ]]; then
        if ! [[ -d $1/$file ]]; then
            mkdir $1/$file
        fi
        cp_file_in_dir $file $1/$file
    elif [[ -f $file ]]; then
        cp "$file" "$1/"
    fi
done
