#!/bin/bash

template=$HOME/dotfiles/script/template/c
files="build.sh .compile .link src/main.c .gitignore"

[[ -d include ]] || mkdir include
[[ -d src ]] || mkdir src

git status > /dev/null 2>&1 && echo "nothing to do with git repo" || git init > /dev/null 2>&1

for fname in $files; do
	[[ -d $(dirname $fname) ]] || mkdir -p $(dirname $fname)
	[[ -f $template/$fname ]] && cp --update $template/$fname $fname
done
