#!/bin/bash

# a build and run script for very specific project setup structure, that there
# should have a build.sh executable file, and then after successfully execute
# the script file, a executable main target file should be generated.

[[ -x ./build.sh ]] || {
    echo "Missing a executable build script: build.sh"; exit 1
}

./build.sh || exit 1

# configure environment variables
[[ -f .env ]] && source .env
[[ -x ./main ]] || {
    echo "Missing a executable target file: ./main"; exit 1
}

./main "$@" || {
    status=$?; echo "Process exited with code: ${status}"; exit "${status}"
}

exit 0
