#!/bin/bash
if [[ -f ./build.sh ]]; then
    STATUS=$(./build.sh)
    if [[ ! $STATUS == 0 ]]; then
        echo "ERROR: build process failed, exiting..."
        exit 1
    elif [[ -f ./main ]]; then
        ./main $*
        STATUS=$?
        if [[ $STATUS == 0 ]]; then
            echo "INFO: Process exited normally"
        else
            echo "INFO: Process exited abnormally with code: ${STATUS}"
            exit 1
        fi
    else 
        echo "ERROR No 'main' executable generated, exiting..."
        exit 1
    fi
else 
    echo "ERROR: no 'build.sh' file found under current directory"
    exit 1
fi
exit 0
