#!/bin/bash

# a build and run script for c-like language. the script expect a build.sh file
# under current directory which also generate a main executable file under the
# same directory.

bash ./build.sh && ./main $*
status=$?

if [[ $status -eq 0 ]]; then
    echo "Process exited normally"
else
    echo "Process exited with code: ${status}"
    exit $status
fi

exit 0
