#!/bin/bash

script_name=$1
script_path=$HOME/dotfiles/script
path_to_script=$script_path/$script_name

function step_failed {
    echo $1 && exit 1
}

for file in $*; do
    [[ -f $path_to_script ]] || step_failed "No such script \'$script_name\' under $script_path"
    [[ $script_name = "del-script" ]] && step_failed "Try not to delete the script which deletes scripts"

    read -r -p "Deleting script \'$script_name\' under $script_path, please confirm. [y/N]: " confirm

    case $confirm in
        [yY][eE][sS]|[yY]|"")
            rm $path_to_script
            echo "Deleted"
            ;;
        [nN][oO]|[nN]|*)
            echo "Aborted"
            ;;
    esac
done
