#!/bin/bash

function step_failed {
    echo $1 && exit 1
}

[[ -z $1 ]] && step_failed "No file name provided"

script_name=$1
script_path=$HOME/dotfiles/script
path_to_script=$script_path/$script_name

[[ -f $path_to_script ]] || step_failed "script with name '$script_name' not found"

if [[ -z $2 ]]; then
    nvim $path_to_script
else
    echo $2 | tee $path_to_script > /dev/null
fi

exit 0
