#!/bin/bash

[[ $TERMINAL = wezterm ]] || {
    echo "Warning: Supports wezterm only" >&2
}

find . -maxdepth 1 -type f -exec basename {} \;\
    | fzf\
    --preview 'chafa\
    -s ${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}\
    --passthrough=tmux\
    -f sixels {}'\
    --cycle\
    --bind 'enter:execute(feh {} &)'
