#!/bin/bash

if [[ -d $HOME/dotfiles/script ]]; then
    while read -r file; do
        [[ -f $file ]] && [[ -x $file ]] && echo $(basename $file)
    done <<< $(find $HOME/dotfiles/script -maxdepth 1)
fi
