#!/bin/bash

while [[ ! -z $1 ]]; do
    case $1 in
        -h|--help)
            echo "Usage: $0 [options] [exe_name]"
            echo "  -h, --help    Show this help message and exit"
            echo "Options:"
            echo "  -s, --summary    Show only the summary"
            exit 0
            ;;
        -s|--summary)
            summary=0
            ;;
        *)
            exe_name=$1
            break
            ;;
    esac
    shift
done

count=0

[[ -z $exe_name ]] && exe_name='firefox'

while read -r line; do
    mem=$(echo $line | awk '{print $1}')
    exe=$(echo $line | awk '{print $2}')
    [[ -z $summary ]] && printf "[$count] %s: %.2f%%\n" $exe $mem
    py_arr="$py_arr$punc$mem"
    punc=", "
    ((count+=1))
done <<< $(ps axo %mem,exe | grep $exe_name)

sum=$(python -c "print(sum([$py_arr]))")

printf "$count processe(s) grepped via \"$exe_name\" used up: %.2f%%\n" $sum
