#!/bin/bash

# FILES=$(find -maxdepth 1 -name '*.pdf')+$(find -maxdepth 1 -name '*.epub')
# FILE=$(echo $FILES | fzf --bind ctrl-l:accept)
FILE=$(find -maxdepth 1 | fzf --bind ctrl-l:accept)

if [[ $? -eq 0 ]]; then
    nohup mupdf "${FILE}" 2&> /dev/null & disown
    exit 0
else
    exit 1
fi
