#!/bin/bash

TEMPLATE=$HOME/dotfiles/script/template
FILES="body.tex build-tex"

git status > /dev/null 2>&1 && echo "nothing to do with git repo" || git init > /dev/null 2>&1

for fname in $FILES; do
	[[ -d $(dirname $fname) ]] || mkdir -p $(dirname $fname)
	cp --update $TEMPLATE/$fname $fname
done
