#!/bin/bash
if [[ -d $1 ]]; then
    cd $1
fi
fzf --no-mouse --cycle --ansi \
    --preview="bat --style numbers --color=always --tabs 4 {} | head -500" \
    --bind ctrl-f:preview-down,ctrl-b:preview-up
