#!/bin/bash

set -o pipefail

sound_effect=${HOME}/Downloads/Hitmarker\ sound.wav
prefix=$HOME/ScreenCap
scrot_flag=("$@" --file "$prefix"/%b%d%Y-%H:%M:%S.png -e "echo \$n")

[[ -d $prefix ]] || mkdir -p "$prefix"

scrot "${scrot_flag[@]}" | tr -d "[:space:]" | xclip -selection clipboard || exit 1

[[ -f $sound_effect ]] && mpv "$sound_effect" > /dev/null 2>&1
