#!/bin/bash
# from thePrimeagen:
# https://github.com/ThePrimeagen/.dotfiles/blob/602019e902634188ab06ea31251c01c1a43d1621/bin/.local/scripts/tmux-sessionizer#L4

selected=${1:-$(find $PWD -type d | fzf)}
[[ -z $selected ]] && ! [[ -d $selected ]] && exit 0

# using full path instead of deriving the basename
# selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s "$selected" -c "$selected"
    exit 0
fi

tmux has-session -t "$selected" 2> /dev/null || tmux new-session -ds "$selected" -c "$selected"
tmux switch-client -t "$selected"
