require("config.catppuccin-nvim")
require("config.evergarden")
require("config.gruvbox")
require("config.kanagawa-nvim")
-- require("config.mellifluous")
require("config.nightfox")
require("config.rose-pine")
require("config.tokyonight-nvim")
require("config.vscode-nvim")
